---
- hosts: all

  tasks:
    - name: Kill all Asterix processes
      shell: 'kill $(jps | egrep ''(CDriver|NCService)'' | awk ''{print $1}'')'

    - name: Remove Asterix installation directory
      file:
        path: /home/couchbase/asterix-install
        state: absent

    - name: Remove Asterix working directories
      file:
        path: "{{ item }}"
        state: absent
      with_items:
        - /hd1/asterix
        - /hd2/asterix
        - /hd3/asterix
        - /hd4/asterix

